### ISSUE TITLE
Add FUNDING.yml

### ISSUE THREAD

**Issue by corasaurus-hex** [distributeaid/next-website-v2#114]
It would be good to add a [`FUNDING.yml`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository) to the project. It makes GitHub show a sponsor button at the top of your repository, which when clicked shows links to how to sponsor the project.

<img width="613" alt="Screenshot 2024-08-18 at 6 25 22 PM" src="https://github.com/user-attachments/assets/846e444e-d131-41e7-9bb7-f4f9f246dfdf">

You can probably just copy the one from [our backend](https://github.com/distributeaid/aggregated-public-information/blob/saga/.github/FUNDING.yml).

**Comment by Taran1508** [comment]
@corasaurus-hex i would like to work on this!

**Comment by Taran1508** [comment]
@corasaurus-hex  i would like to work on this!

**Comment by swizzard** [comment]
@Taran1508 i'm going to take this over if that's alright.

**Comment by Taran1508** [comment]
@swizzard can I do this? I would love to work upon this!!

**Comment by swizzard** [comment]
@Taran1508 i'm so sorry! i missed your comment entirely. if you want to take this over or amend it at all please do.

**Comment by Taran1508** [comment]
@swizzard No worries! I'll take it over—please assign me!

**Comment by swizzard** [comment]
@Taran1508 assigned! have at it

**Comment by Taran1508** [comment]
@swizzard Thank you, I'll finish it in a day😊
