### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by corasaurus-hex** [distributeaid/next-website-v2#115]
It would be good to add a [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) to this repo. You can see [an example from our backend](https://github.com/distributeaid/aggregated-public-information/blob/saga/.github/pull_request_template.md) but maybe we should tailor this for frontend needs?

**Comment by CatherineKiiru** [comment]
@corasaurus-hex can I work on this?

**Comment by swizzard** [comment]
@CatherineKiiru i'm going to take this over if that's alright.

**Comment by CatherineKiiru** [comment]
@swizzard go right ahead!

**Comment by jtfairbank** [comment]
Closed by #194
