### ISSUE TITLE
Migrate the tech page

### ISSUE THREAD

**Issue by CatherineKiiru** [distributeaid/next-website-v2#2]
### Overview

The task is to migrate the [current tech page](https://distributeaid.org/tech/oss-explorers/) to the NextJS website. We'll also use Tailwind & TypeScript for the new website. Check out [this repo](https://github.com/distributeaid/distributeaid.org) to get the specs for the current website

### Scope
- [ ] Design / Frontend (pages & components)

### Relation to DA

- [ ] User - I use DA's projects in my own learning, research, or work.
- [ ] Contributor - I volunteer with DA or contribute to it's projects.

### Followup

- [X] Contribute content or code to help resolve this issue.
- [X] Review & test the changes to help decide if the issue is resolved.

### IP Ownership

The materials are available under an open-source / open-content license (MIT, Creative Commons, etc).

### Attestations & Copyright Assignment

- [X] To assign Distribute Aid the copyright of any materials you created specifically for this project.
- [X] That Distribute Aid has the rights to use any materials you submit which were created by you or others for general use.
- [X] That you have specified any additional licensing requirements related to the materials (crediting the original creators, licensing fees, etc).
- [X] That the materials are not also encumbered by a patent or other types of intellectual property that limit our ability to use them.

### Code of Conduct

- [X] I agree to follow Distribute Aid's Code of Conduct.

**Comment by Lovelyfin00** [comment]
I’d like to work on this @CatherineKiiru
