### ISSUE TITLE
Create the new About Us Page

### ISSUE THREAD

**Issue by jtfairbank** [distributeaid/next-website-v2#217]
There are follow up issues after this one is completed, so hoping to have it done by Monday the 25th latest. :smile: 

**Design:** [See this Figma file.](https://www.figma.com/design/Yq8LKeIVka701hYL45heud/Colors-for-DA?node-id=427-3392&m=dev)

![Screenshot from 2024-11-12 02 17 23@2x](https://github.com/user-attachments/assets/29f96fb0-839c-45ca-b86c-e8106e331be6)

**Code:**

-  See `src/app/about-us/page.tsx` for the code.  The new design departs significantly from the current page, so you can either empty that file and start from scratch, or create a new file for your work in progress.
 - Put page-content-specific components in `src/components/about-us/` or in another components folder if they're potentially reusable on other pages.  It's ok to have both new & old components in the `about-us/` folder, as we'll remove the old ones once the new page replaces the old one.

**Notes:**

- Don't worry about the "Our History" section of the page when working on this issue.  I'd like to get this one done first to get the new page setup, and then we'll tackle that section in a follow-up issue.
- Since we're making a new page with a significantly different design than the old one, there shouldn't need to be too much code reuse.  Let's prioritize using [Radix UI](https://www.radix-ui.com/) components (check both their [Theme](https://www.radix-ui.com/themes/docs/overview/getting-started) and [Primitives](https://www.radix-ui.com/primitives/docs/overview/introduction) docs).   It's ok to sprinkle in some tailwind in order to go above and beyond what we get out of the box with Radix, but don't feel like you need to be pixel-perfect when following the designs.

**Comment by Harshvardhan1012** [comment]
Can you assign this issue to me

**Comment by jtfairbank** [comment]
Hey @Harshvardhan1012 could you email `tech @ distributeaid . org` to introduce yourself? We're primarily looking for contributors with existing webdev experience who have the time to make regular contributions, so please be sure to highlight that. If you're looking for a way to gain experience doing web development, our [Open Source Explorers](https://distributeaid.org/tech/oss-explorers/) program may be a better fit. 😄

**Comment by tahirxx** [comment]
Hi @Harshvardhan1012 , I started working on the About-us-page. Im sorry I thought i assigned myself yesterday, But accidently unassigned myself also. We can work together on it.

**Comment by Harshvardhan1012** [comment]
Hey @tahirxx  I am almost finished with the entire page with just the history section left which is also halfway done. Would you like to help me out with that?

**Comment by tahirxx** [comment]
@Harshvardhan1012 Same. No worries. I’ll grab another card. Thanks .
