### ISSUE TITLE
Migrate About Us Page

### ISSUE THREAD

**Issue by CatherineKiiru** [distributeaid/next-website-v2#5]
## Description
The current[ about Us page](https://distributeaid.org/about-us/) needs to be migrated to the new website with NextJS, TypeScript and Tailwind. Refer to this repo to get the specs for the pagehttps://github.com/distributeaid/distributeaid.org 

Tasks
- [ ] Migrate the current About Us to NextJS.
- [ ] The "Our History" should start from the recent year down to the 2018.The current implementation starts from 2018 and should be changed. See the screenshot below:

## Screenshot
![Screenshot from 2024-02-22 10-08-12](https://github.com/distributeaid/next-website/assets/66266208/8fbb825b-3a8f-40e3-bf28-c7b88efa1414)

### Scope
- [X] Design / Frontend (pages & components)

### Relation to DA

- [X] Contributor - I volunteer with DA or contribute to it's projects.

### Followup

- [X] Contribute content or code to help resolve this issue.
- [ ] Review & test the changes to help decide if the issue is resolved.

### IP Ownership

Others created the materials, and DA can purchase a private license to use them.

### Attestations & Copyright Assignment

- [X] To assign Distribute Aid the copyright of any materials you created specifically for this project.
- [X] That Distribute Aid has the rights to use any materials you submit which were created by you or others for general use.
- [X] That you have specified any additional licensing requirements related to the materials (crediting the original creators, licensing fees, etc).
- [X] That the materials are not also encumbered by a patent or other types of intellectual property that limit our ability to use them.

### Code of Conduct

- [X] I agree to follow Distribute Aid's Code of Conduct.

**Comment by CatherineKiiru** [comment]
@Jybium I've already create a folder for the about us page, so no need to create a new one

**Comment by Jybium** [comment]
@CatherineKiiru I have created a pull request to this issue, kindly review it.
