### ISSUE TITLE
Fix(deps) - Migrate npm to Yarn v4.4.0 (Latest Version)

### ISSUE THREAD

**Issue by CatherineKiiru** [distributeaid/next-website-v2#80]
### Why?
Migrating to yarn to maintain package manager consistency across client side and our backend

**Comment by MatrixFrog** [comment]
Should we delete the package-lock.json then? Or do we want to keep both npm and yarn support for a little while?

**Comment by CatherineKiiru** [comment]
We can delete package-lock.json and maintain yarn only
