### ISSUE TITLE
Setup ESLint

### ISSUE THREAD

**Issue by jtfairbank** [distributeaid/next-website-v2#92]
ESLint is a static code analysis tool that helps identify issues with Javascript / JSX / Typescript / TSX code!  It'll help us ensure consistency and prevent bugs.

The backend project already has this setup in this [Pull Request](https://github.com/distributeaid/aggregated-public-information/pull/86) to see how they did it.  Pay attention to the scripts that are setup and packages that are installed in [package.json](https://github.com/distributeaid/aggregated-public-information/blob/feat/85/upgrade-to-strapi-5/package.json) as well as the configuration in [eslint.config.mjs](https://github.com/distributeaid/aggregated-public-information/blob/feat/85/upgrade-to-strapi-5/eslint.config.mjs).

- [ ] Setup ESLint
- [ ] Add `package.json` commands to run it.
- [ ] Document the commands in the `readme.md` file.

**Comment by MatrixFrog** [comment]
There might be more tweaks we want to make to the configuration but I would say this is essentially done.
