### ISSUE TITLE
Setup Typescript Checking

### ISSUE THREAD

**Issue by jtfairbank** [distributeaid/next-website-v2#94]
TSC is TypeScript's commandline tool for checking our types usage.  It'll help make sure we're using types properly, and identify problems with them.

The backend project already has this setup in this [Pull Request](https://github.com/distributeaid/aggregated-public-information/pull/86) to see how they did it.  Pay attention to the scripts that are setup and packages that are installed in [package.json](https://github.com/distributeaid/aggregated-public-information/blob/feat/85/upgrade-to-strapi-5/package.json) .

- [ ] Add `package.json` commands to run tsc type checking.
- [ ] Document the commands in the `readme.md` file.

**Comment by MatrixFrog** [comment]
Will take a stab at this, it should be easier than the other workflow I was trying to make.
